### ISSUE TITLE
support for building reqwest with rustls for tls

### ISSUE THREAD

**Issue by Lunarequest** [jerusdp/hcaptcha-rs#370]
Currently reqwest is built with openssl for tls on linux. There are benefits to using rustls over openssl which seems to be plagued by  regressions CVE's and generally bad practices. This would also be useful for people who are using this in projects that use distroless containers to drop the need to statically compile openssl into their binaries.

**Comment by Lunarequest** [comment]
@jerusdp do you know when the next release will be published? I'd like to start building hcaptcha with rustsl but i would prefer to avoid using git deps

**Comment by jerusdp** [comment]
Luna, 

I expect to complete the next release by the weekend.

Regards, 

Jerry

**Comment by Lunarequest** [comment]
Thanks for the info! I will be awaiting it patiently(I'm also going to close this issue since its solved)

**Comment by jerusdp** [comment]
@Lunarequest  the update is released

**Comment by Lunarequest** [comment]
thanks!
