### ISSUE TITLE
Secret Key not working

### ISSUE THREAD

**Issue by ExoSkye** [jerusdp/hcaptcha-rs#808]
Hi,
I'm trying to use this library with a secret key that's in the format `ES_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx` where `x` is a hex digit
however this library appears to be using 40 digit long hex strings? I have no idea what these are or where they come from, since I was given that as my secret

What am I like, doing wrong here?

**Comment by jerusdp** [comment]
The secret issued from the hcaptcha site is a hex number. There is no prefix. Have you tried dropping the "ES_"?

See test example keys [here](https://docs.hcaptcha.com/#test-key-set-enterprise-account-bot-detected) in the hcaptcha dev docs.

**Comment by ExoSkye** [comment]
I'm pretty sure that's out of date - I can see multiple accounts saying they updated it
also, without the prefix the key is 32 hex digits, not 40 long, so it still doesn't work

For example, here: https://www.phpbb.com/customise/db/extension/hcaptcha/support/topic/244255

**Comment by jerusdp** [comment]
The extended validation is causing your error. To remove it using the following in Cargo.toml:

hcaptcha = { version="2.2.2", default-features = false, features = ["nativetls-backend"]}

**Comment by ExoSkye** [comment]
Surely that's not a permanent fix, right? This should in theory be a reason for a new version (2.3.0?) that supports it?

**Comment by jerusdp** [comment]
There will be a new version ... working on it

**Comment by jerusdp** [comment]
Version 2.3.0 published.
